name: Build MagicCam
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      # 新增：把模块文件打包成zip（Magisk模块标准打包）
      - name: Package Magisk Module Zip
        run: |
          zip -r MagicCam-Module.zip . -i "module.prop" -i "system/**/*" -i "*.so"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MagicCam-Module
          path: MagicCam-Module.zip
